### PR TITLE
TabBarView Update

### PR DESCRIPTION
**Pull request by Ivan-Skoryk**
## Summary
 Updated tab bar items icons. Adjusted UI for all devices. Added empty… method for calibration routing.
 Ticket: https://trello.com/c/LBUKeNQg

 #### Checklist:
 - [x] I have added a brief description of the problem in the PR body.
 - [x] I have explained how I solved the problem in the PR body.
 - [x] I have covered possible edge cases and side effects.
 - [x] I have have attached screenshots to the PR of any UI change.
 - [x] I have checked that my changes work on iOS and macOS targets.
 - [x] I have checked that my changes work correctly on devices with and without a Home button.
 - [x] I have added unit tests for the new logic.
 - [x] I have achieved maximum possible code coverage for the new code.
 - [x] I have checked that my UI works correctly on both Light and Dark themes.

 #### Screenshots or GIFs

iPhone 8
image

iPhone 7+
image
image

iPhone X
image

iPhone SE
image

Mac OS
image

### CODE REVIEW

**Comment by Ivan-Skoryk** [comment]
@Artem-Kalmykov this UI structure will be OK?
image

**Comment by Artem-Kalmykov** [comment]
@Ivan-Skoryk This wouldn't have a tap animation. Use UIButton, there are a couple of approaches to implement it like on the design. See https://stackoverflow.com/questions/4201959/label-under-image-in-uibutton

**Comment by Ivan-Skoryk** [comment]
@Artem-Kalmykov I had used the extension mentioned in stackoverflow question. Check pls.

**Comment by Artem-Kalmykov** [comment]
1. The UI became incorrect now, the image is out of button's bounds:
Screenshot 2020-03-19 at 13 10 32

2. 
```
[calibrationButton, chartButton, plusButton, historyButton, settingsButton].forEach { (button) in
            button?.centerVertically()
        }
```
 is not ok. Create a separate class for such button, e.g. `final class CenteredTitleButton: UIButton`. Move the extension logic there and remove the extension.

**Comment by Ivan-Skoryk** [comment]
@Artem-Kalmykov check pls

**Comment by Artem-Kalmykov** [comment]
@Ivan-Skoryk Better now, but still a couple of changes are required:
1. On iPhone X buttons seems to be located higher than expected. Please refer to the design, we might need to reduce tab bar view height.
2. The tab bar view itself has a border or shadow at the top. Refer to the design and implement as expected.
3. Code style changes required for `CenteredTitleButton.swift`:
- Make the class `final` if you're not subclassing it.
- When making multi-lined function calls follow the pattern, e.g. instead of
```
return CGRect(x: 0, y: contentRect.height - rect.height,
            width: contentRect.width, height: rect.height)
```
it should be
Screenshot 2020-03-19 at 14 22 51
with each argument on a new line. Apply it to all the other parts of the code.
- Arithmetical operators should have spaces before and after, e.g. replace
```
contentRect.width/2.0
```
with
```
contentRect.width / 2.0
```

**Comment by Ivan-Skoryk** [comment]
@Artem-Kalmykov check pls

**Comment by Artem-Kalmykov** [comment]
@Ivan-Skoryk 
1. Colors should not be hardcoded in the interface builder. Move them to `Assets.xcassets` -> `Colors`. Also, they might differ for the dark theme, so think about it.
2. The font for button titles is incorrect. It is `Medium` in the design, but you have it as `Regular`.
3. Buttons offset is still incorrect. Top spacing from button image to top border is `7.6` pixels in the design (assume `8.0`), but it is `6.0` currently.
4. The background color of the tab bar in light theme is different from the design.
5. Border color is incorrect, it should be `198.0 / 255.0` in sRGB.

**Comment by Ivan-Skoryk** [comment]
@Artem-Kalmykov check pls

**Pull request merged**
